export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const FETCH_ACCOUNT_PENDING = 'FETCH_ACCOUNT_PENDING';
export const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_ERROR = 'FETCH_ACCOUNT_ERROR';

export const FETCH_LOAN_PENDING = 'FETCH_LOAN_PENDING';
export const FETCH_LOAN_SUCCESS = 'FETCH_LOAN_SUCCESS';
export const FETCH_LOAN_ERROR = 'FETCH_LOAN_ERROR';

export const LOAN_CHECK = 'LOAN_CHECK';
export const LOAN_UNCHECK = 'LOAN_UNCHECK';
export const LOAN_SORT = 'LOAN_SORT';